---
# TODO: install jemalloc by default

- name: Directory Exists | fluentd config roots
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: wcadmin
    mode: 775
  with_items:
    - "{{ fluentd_config_root }}"
    - "{{ fluentd_config_include_root }}"
  tags:
    - directory-structure
    - configuration
    - ansible

- name: "Upload Config | {{ fluentd_config_path }}"
  template:
    src: usr/local/etc/fluentd/fluentd.conf
    dest: "{{ fluentd_config_path }}"
    owner: root
    group: wcadmin
    mode: 0664
  notify: Reload Service | fluentd
