---
- name: Upload Config | fluentd
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: wcadmin
    mode: 0664
  with_items:
    - etc/td-agent/td-agent.conf
  notify: Reload Service | fluentd

- name: "Directory Exists | {{ fluentd_config_include_path }}"
  file:
    state: directory
    path: "{{ fluentd_config_include_path }}"
    owner: root
    group: wcadmin
    mode: 775
  tags:
    - directory-structure
    - configuration
    - ansible
