---
- name: Install Packages | apt | libjemalloc1
  apt:
    state: latest
    pkg: libjemalloc1
  tags:
    - software-installation
    - using-apt
    - jemalloc
    - build-dependency

- name: Install Packages | apt | libcurl4-openssl-dev
  apt:
    state: latest
    pkg: libcurl4-openssl-dev
  when: "'elasticsearch' in fluentd_plugins"
  tags:
    - software-installation
    - using-apt
    - fluentd-plugin-elasticsearch
    - build-dependency

- name: Install Packages | gem
  gem:
    state: latest
    name: "fluent-plugin-{{ item }}"
    user_install: no
  with_items: fluentd_plugins
  when: fluentd_plugins is iterable
  tags:
    - software-installation
    - using-gem
    - fluentd

