---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - td-agent
  tags:
    - software-installation
    - using-apt
    - fluentd

- name: Install Packages | gem
  gem:
    state: latest
    name: "fluent-plugin-{{ item }}"
    user_install: no
  with_items: fluentd_plugins
  when: fluentd_plugins is iterable
  tags:
    - software-installation
    - using-gem
    - fluentd